cmake specific version for windows?

diff --git a/.github/workflows/Ubuntu.yml b/.github/workflows/Ubuntu.yml
--- a/.github/workflows/Ubuntu.yml
+++ b/.github/workflows/Ubuntu.yml
@@ -66,17 +66,11 @@ jobs:
     steps:
     - uses: actions/checkout@v2
 
-  # Install pinned version of cmake, incase new releases break things like google test...
+    # Install pinned version of cmake, incase new releases break things like google test...
     - name: Install Specific Cmake version via Pip.
       run: |
-        cmake --version
-        python3 -m pip install cmake==3.18.4
         python3 -m pip install --user cmake==3.18.4
-        python3 -m site --user-base
         echo "$(python3 -m site --user-base)/bin" >> $GITHUB_PATH
-        cmake --version
-        ls /home/runner/.local/
-        ls /home/runner/.local/bin
 
     - name: cmake version?
       run: |
@@ -85,50 +79,50 @@ jobs:
         echo "${PATH}"
 
 
-    # - name: Install CUDA
-    #   env:
-    #     cuda: ${{ matrix.cuda }}
-    #   run: |
-    #     source ./scripts/actions/install_cuda_ubuntu.sh
-    #     if [[ $? -eq 0 ]]; then
-    #       # Set paths for subsequent steps, using ${CUDA_PATH}
-    #       echo "Adding CUDA to CUDA_PATH, PATH and LD_LIBRARY_PATH"
-    #       echo "CUDA_PATH=${CUDA_PATH}" >> $GITHUB_ENV
-    #       echo "${CUDA_PATH}/bin" >> $GITHUB_PATH
-    #       echo "LD_LIBRARY_PATH=${CUDA_PATH}/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
-    #     fi
-    #   shell: bash
+    - name: Install CUDA
+      env:
+        cuda: ${{ matrix.cuda }}
+      run: |
+        source ./scripts/actions/install_cuda_ubuntu.sh
+        if [[ $? -eq 0 ]]; then
+          # Set paths for subsequent steps, using ${CUDA_PATH}
+          echo "Adding CUDA to CUDA_PATH, PATH and LD_LIBRARY_PATH"
+          echo "CUDA_PATH=${CUDA_PATH}" >> $GITHUB_ENV
+          echo "${CUDA_PATH}/bin" >> $GITHUB_PATH
+          echo "LD_LIBRARY_PATH=${CUDA_PATH}/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
+        fi
+      shell: bash
 
-    # # Specify the correct host compilers
-    # - name: Install/Select gcc and g++ 
-    #   run: |
-    #     sudo apt-get install -y gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }}
-    #     echo "CC=/usr/bin/gcc-${{ matrix.gcc }}" >> $GITHUB_ENV
-    #     echo "CXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
-    #     echo "CUDAHOSTCXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
+    # Specify the correct host compilers
+    - name: Install/Select gcc and g++ 
+      run: |
+        sudo apt-get install -y gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }}
+        echo "CC=/usr/bin/gcc-${{ matrix.gcc }}" >> $GITHUB_ENV
+        echo "CXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
+        echo "CUDAHOSTCXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
 
-    # - name: Configure cmake
-    #   id: configure
-    #   run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }}
+    - name: Configure cmake
+      id: configure
+      run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }}
 
-    # - name: Configure Error Processing
-    #   if: ${{ failure() && steps.configure.outcome == 'failure' }}
-    #   working-directory: ${{ env.build_dir }}
-    #   run: |
-    #       if [[ -f "CMakeFiles/CMakeOutput.log" ]]; then
-    #         echo "---- CMakeFiles/CMakeOutput.log"
-    #         cat CMakeFiles/CMakeOutput.log
-    #         echo "----"
-    #       fi
-    #       if [[ -f "CMakeFiles/CMakeError.log" ]]; then
-    #         echo "---- CMakeFiles/CMakeError.log"
-    #         cat CMakeFiles/CMakeError.log
-    #         echo "----"
-    #       fi
+    - name: Configure Error Processing
+      if: ${{ failure() && steps.configure.outcome == 'failure' }}
+      working-directory: ${{ env.build_dir }}
+      run: |
+          if [[ -f "CMakeFiles/CMakeOutput.log" ]]; then
+            echo "---- CMakeFiles/CMakeOutput.log"
+            cat CMakeFiles/CMakeOutput.log
+            echo "----"
+          fi
+          if [[ -f "CMakeFiles/CMakeError.log" ]]; then
+            echo "---- CMakeFiles/CMakeError.log"
+            cat CMakeFiles/CMakeError.log
+            echo "----"
+          fi
 
 
 
-    # - name: Build everything else
-    #   working-directory: ${{ env.build_dir }}
-    #   run: cmake --build . --target all --verbose -j `nproc`
+    - name: Build everything else
+      working-directory: ${{ env.build_dir }}
+      run: cmake --build . --target all --verbose -j `nproc`
 
