Tidy, document github actions vs2017+cuda compat, and try on.push.paths

diff --git a/.github/workflows/windowsVisualStudio2019.yml b/.github/workflows/windowsVisualStudio2019.yml
--- a/.github/workflows/windowsVisualStudio2019.yml
+++ b/.github/workflows/windowsVisualStudio2019.yml
@@ -1,9 +1,14 @@
+# VS2019 supports CUDA 10.1+
 name: WindowsVisualStudio2019
-# CUDA 10.1 for VS2019
 
 on:
   push:
     branches: [ master ]
+    paths:
+      # Don't trigger on workflow changes
+      "!.github/workflows/**"
+      # Except for this workflow
+      ".github/workflows/windowsVisualStudio2019"
   pull_request:
     branches: [ master ]
 
@@ -26,11 +31,12 @@ jobs:
         # Install CUDA via a powershell script
         .\scripts\install_cuda_windows.ps1
         # Abort if the script returned an error code
-        if (!$?) { exit 1 }
-        # Set paths for subsequent steps, using $env:CUDA_PATH
-        echo "::set-env name=CUDA_PATH::$env:CUDA_PATH"
-        echo "::set-env name=$env:CUDA_PATH_VX_Y::$env:CUDA_PATH"
-        echo "::add-path::$env:CUDA_PATH/bin"
+        if ($?) {
+          # Set paths for subsequent steps, using $env:CUDA_PATH
+          echo "::set-env name=CUDA_PATH::$env:CUDA_PATH"
+          echo "::set-env name=$env:CUDA_PATH_VX_Y::$env:CUDA_PATH"
+          echo "::add-path::$env:CUDA_PATH/bin"
+        }
       shell: powershell
 
     - name: Install cpplint
@@ -38,11 +44,30 @@ jobs:
         python -m pip install --upgrade cpplint
 
     - name: Configure CMake
+      id: configure
       run: |
         mkdir -p build
         cd build
         cmake .. -G "${{ env.visual_studio }}" -A x64
+        #  -DCUDA_TOOLKIT_ROOT_DIR="$CUDA_PATH"
+        status=$? 
       shell: bash
+
+    - name: Configure Error Processing
+      run: |
+          if [[ -f "CMakeFiles/CMakeOutput.log" ]]; then
+            echo "---- CMakeFiles/CMakeOutput.log"
+            cat CMakeFiles/CMakeOutput.log
+            echo "----"
+          fi
+          if [[ -f "CMakeFiles/CMakeError.log" ]]; then
+            echo "---- CMakeFiles/CMakeError.log"
+            cat CMakeFiles/CMakeError.log
+            echo "----"
+          fi
+      shell: bash
+      working-directory: build
+      if: ${{ failure() && steps.configure.outcome == 'failure' }}
 
     - name: Build
       run: cmake --build . --config Release -t ALL_BUILD --verbose
