Do no pip install --user on windows?

diff --git a/.github/workflows/Windows.yml b/.github/workflows/Windows.yml
--- a/.github/workflows/Windows.yml
+++ b/.github/workflows/Windows.yml
@@ -56,7 +56,7 @@ jobs:
     - name: Install Specific Cmake version via Pip.
       shell: bash
       run: |
-        python -m pip install --user cmake==3.18.0
+        python -m pip install cmake==3.18.0
         which python
         echo "$(python -m site --user-base)/bin"
         echo "$(python -m site --user-base)/bin" >> $GITHUB_PATH
@@ -68,55 +68,55 @@ jobs:
         cmake --version
         echo "${PATH}"
 
-    - name: Install CUDA
-      env: 
-        cuda: ${{ matrix.cuda }}
-        visual_studio: ${{ matrix.visual_studio }}
-      shell: powershell
-      run: |
-        # Install CUDA via a powershell script
-        .\scripts\actions\install_cuda_windows.ps1
-        if ($?) {
-          # Set paths for subsequent steps, using $env:CUDA_PATH
-          echo "Adding CUDA to CUDA_PATH, CUDA_PATH_X_Y and PATH"
-          echo "CUDA_PATH=$env:CUDA_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
-          echo "$env:CUDA_PATH_VX_Y=$env:CUDA_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
-          echo "$env:CUDA_PATH/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
-        }
+    # - name: Install CUDA
+    #   env: 
+    #     cuda: ${{ matrix.cuda }}
+    #     visual_studio: ${{ matrix.visual_studio }}
+    #   shell: powershell
+    #   run: |
+    #     # Install CUDA via a powershell script
+    #     .\scripts\actions\install_cuda_windows.ps1
+    #     if ($?) {
+    #       # Set paths for subsequent steps, using $env:CUDA_PATH
+    #       echo "Adding CUDA to CUDA_PATH, CUDA_PATH_X_Y and PATH"
+    #       echo "CUDA_PATH=$env:CUDA_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
+    #       echo "$env:CUDA_PATH_VX_Y=$env:CUDA_PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
+    #       echo "$env:CUDA_PATH/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
+    #     }
 
-    - name: nvcc check
-      shell: powershell
-      run: |
-        nvcc -V
-        ls $env:CUDA_PATH
-        ls $env:CUDA_PATH\bin
-        ls $env:CUDA_PATH\include
+    # - name: nvcc check
+    #   shell: powershell
+    #   run: |
+    #     nvcc -V
+    #     ls $env:CUDA_PATH
+    #     ls $env:CUDA_PATH\bin
+    #     ls $env:CUDA_PATH\include
 
-    - name: cmake version
-      shell: bash
-      run: cmake --version
+    # - name: cmake version
+    #   shell: bash
+    #   run: cmake --version
 
-    - name: Configure CMake
-      id: configure
-      shell: bash
-      run: cmake . -B ${{ env.build_dir }} -G "${{ matrix.visual_studio }}" -A x64 
+    # - name: Configure CMake
+    #   id: configure
+    #   shell: bash
+    #   run: cmake . -B ${{ env.build_dir }} -G "${{ matrix.visual_studio }}" -A x64 
 
-    - name: Configure Error Processing
-      if: ${{ (failure() && steps.configure.outcome == 'failure') || success() }}
-      working-directory: ${{ env.build_dir }}
-      shell: bash
-      run: |
-          if [[ -f "CMakeFiles/CMakeOutput.log" ]]; then
-            echo "---- CMakeFiles/CMakeOutput.log"
-            cat CMakeFiles/CMakeOutput.log
-            echo "----"
-          fi
-          if [[ -f "CMakeFiles/CMakeError.log" ]]; then
-            echo "---- CMakeFiles/CMakeError.log"
-            cat CMakeFiles/CMakeError.log
-            echo "----"
-          fi
+    # - name: Configure Error Processing
+    #   if: ${{ (failure() && steps.configure.outcome == 'failure') || success() }}
+    #   working-directory: ${{ env.build_dir }}
+    #   shell: bash
+    #   run: |
+    #       if [[ -f "CMakeFiles/CMakeOutput.log" ]]; then
+    #         echo "---- CMakeFiles/CMakeOutput.log"
+    #         cat CMakeFiles/CMakeOutput.log
+    #         echo "----"
+    #       fi
+    #       if [[ -f "CMakeFiles/CMakeError.log" ]]; then
+    #         echo "---- CMakeFiles/CMakeError.log"
+    #         cat CMakeFiles/CMakeError.log
+    #         echo "----"
+    #       fi
 
-    - name: Build
-      working-directory: ${{ env.build_dir }}
-      run: cmake --build . --config ${{ env.config }} --target ALL_BUILD --verbose
+    # - name: Build
+    #   working-directory: ${{ env.build_dir }}
+    #   run: cmake --build . --config ${{ env.config }} --target ALL_BUILD --verbose
